spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect  # Dialect 설정
      ddl-auto: update  # create, update, validate 등으로 설정 가능
      format_sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio  # MySQL 데이터베이스 URL
    username: root  # MySQL 사용자 이름
    password: 1213  # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스 이름
  h2:
    console:
      enabled: false  # H2 콘솔 비활성화
